
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char AIRMapComponentName[];

JSI_EXPORT extern const char AIRMapMarkerComponentName[];

JSI_EXPORT extern const char AIRMapPolylineComponentName[];

JSI_EXPORT extern const char AIRMapPolygonComponentName[];

JSI_EXPORT extern const char AIRMapCircleComponentName[];

JSI_EXPORT extern const char AIRMapCalloutComponentName[];

JSI_EXPORT extern const char AIRMapCalloutSubviewComponentName[];

JSI_EXPORT extern const char GeojsonComponentName[];

JSI_EXPORT extern const char AIRMapUrlTileComponentName[];

JSI_EXPORT extern const char AIRMapWMSTileComponentName[];

JSI_EXPORT extern const char AIRMapOverlayComponentName[];

/*
 * `ShadowNode` for <AIRMap> component.
 */
using AIRMapShadowNode = ConcreteViewShadowNode<AIRMapComponentName, ViewProps, AIRMapEventEmitter>;

using AIRMapMarkerShadowNode = ConcreteViewShadowNode<AIRMapMarkerComponentName, ViewProps, AIRMapMarkerEventEmitter>;

using AIRMapPolylineShadowNode = ConcreteViewShadowNode<AIRMapPolylineComponentName, ViewProps, AIRMapPolylineEventEmitter>;

using AIRMapPolygonShadowNode = ConcreteViewShadowNode<AIRMapPolygonComponentName, ViewProps, AIRMapPolygonEventEmitter>;

using AIRMapCircleShadowNode = ConcreteViewShadowNode<AIRMapCircleComponentName, ViewProps, AIRMapCircleEventEmitter>;

using AIRMapCalloutShadowNode = ConcreteViewShadowNode<AIRMapCalloutComponentName, ViewProps, AIRMapCalloutEventEmitter>;

using AIRMapCalloutSubviewShadowNode = ConcreteViewShadowNode<AIRMapCalloutSubviewComponentName, ViewProps, AIRMapCalloutSubviewEventEmitter>;

using GeojsonShadowNode =ConcreteViewShadowNode<GeojsonComponentName, ViewProps, GeojsonEventEmitter>;

using AIRMapUrlTileShadowNode = ConcreteViewShadowNode<AIRMapUrlTileComponentName, ViewProps, AIRMapUrlTileEventEmitter>;

using AIRMapWMSTileShadowNode = ConcreteViewShadowNode<AIRMapWMSTileComponentName, ViewProps, AIRMapWMSTileEventEmitter>;

using AIRMapOverlayShadowNode = ConcreteViewShadowNode<AIRMapOverlayComponentName, ViewProps, AIRMapOverlayEventEmitter>;

} // namespace react
} // namespace facebook
